# Service
apiVersion: v1
kind: Service
metadata:
  name: app3-service
  annotations:
    spec.ingressClassName: traefik_app3
    # spec.defaultBackend: traefik_app3
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP 
      port: 80
  type: ClusterIP