# Service
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  selector:
    app: app1 
  ports:
    - protocol: TCP 
      port: 80
      # targetPort: 8080
  type: ClusterIP
  # type: NodePort


# le nom de l'application app1
# le port http (dans notre cas) de notre application: 8080
# le port exposé: 80



