apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap2
data:
  index.html: |
    <html>
    <head>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f0f0f0;
                text-align: center;
            }
            .container {
                background-color: #ffffff;
                border-radius: 10px;
                padding: 20px;
                margin: 20px auto;
                width: 80%;
                max-width: 600px;
            }
            h1 {
                color: #007bff;
            }
            p {
                font-size: 18px;
                color: #333;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Welcome to Kubernetes Cluster</h1>
            <p>Hello from App2</p>
        </div>
    </body>
    </html>