# cat /var/log/k3s-agent.log

IMAGE = "generic/alpine37"
MEMORY = 1024
CPUS = 1
S_HOSTNAME = "ndormoyS"
W_HOSTNAME = "ndormoySW"
S_IP = "192.168.56.110"
W_IP = "192.168.56.111"

# Extra parameters in INSTALL_K3S_EXEC variable because of
# K3s picking up the wrong interface when starting server and agent
# https://github.com/alexellis/k3sup/issues/306

server_script = <<-SHELL
    sudo -i
    apk add curl

    rm -rf /vagrant/server_node_token
    mkdir -p /vagrant/server_node_token

    # export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --bind-address=#{S_IP} --node-external-ip=#{S_IP} --flannel-iface=eth1"
    export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --bind-address=#{S_IP} --flannel-iface=eth1"

    echo "INSTALL_K3S_EXEC : ${INSTALL_K3S_EXEC}"
    export KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
    echo "KUBECONFIG : ${KUBECONFIG}"

    curl -sfL https://get.k3s.io | sh -
    echo "Sleeping for 5 seconds to wait for k3s to start"
    sleep 15
    sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/server_node_token/
    echo "/var/lib/rancher/k3s/server/node-token : $(cat /var/lib/rancher/k3s/server/node-token)"
    chmod 755 -R /vagrant/server_node_token/

    chmod 755 /etc/rancher/k3s/k3s.yaml
    sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/server_node_token/

    echo "/etc/rancher/k3s/k3s.yaml : $(cat /etc/rancher/k3s/k3s.yaml)"
    SHELL

agent_script = <<-SHELL
    sudo -i
    apk add curl
    export KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
    echo "KUBECONFIG : ${KUBECONFIG}"
    sudo cp /vagrant/server_node_token/k3s.yaml /etc/rancher/k3s/k3s.yaml

    echo "/etc/rancher/k3s/k3s.yaml : $(cat /etc/rancher/k3s/k3s.yaml)"
    export K3S_TOKEN_FILE=/vagrant/server_node_token/node-token

    echo "K3S_TOKEN_FILE : ${K3S_TOKEN_FILE}"
    export K3S_URL=https://#{S_IP}:6443
    echo "K3S_URL : ${K3S_URL}"
    export INSTALL_K3S_EXEC="--flannel-iface=eth1"
    echo "INSTALL_K3S_EXEC : ${INSTALL_K3S_EXEC}"
    curl -sfL https://get.k3s.io | sh -
    SHELL

#-----------------------------Base Configuration------------------------
Vagrant.configure("2") do |config|
  config.vm.box = IMAGE
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = MEMORY
    vb.cpus = CPUS
  end
  config.vm.synced_folder ".", "/vagrant"

#---------------------------Server--------------------------------------
  config.vm.define S_HOSTNAME, primary: true do |server|
    server.vm.network "private_network", ip: S_IP
    server.vm.hostname = S_HOSTNAME
    server.vm.provider "virtualbox" do |vb|
      vb.name = S_HOSTNAME
    end
    server.vm.provision "shell", inline: server_script
  end

#---------------------------Worker--------------------------------------
    config.vm.define W_HOSTNAME do |worker|
      worker.vm.network "private_network", ip: W_IP
      worker.vm.hostname = W_HOSTNAME
      worker.vm.provider "virtualbox" do |vb|
        vb.name = W_HOSTNAME
      end
      worker.vm.provision "shell", inline: agent_script
    end
end