# -*- mode: ruby -*-
# vi: set ft=ruby :

# cat /var/log/k3s-agent.log


server_ip = "192.168.56.110"

agents = { "agent1" => "192.168.56.111" }

# Extra parameters in INSTALL_K3S_EXEC variable because of
# K3s picking up the wrong interface when starting server and agent
# https://github.com/alexellis/k3sup/issues/306

server_script = <<-SHELL
    sudo -i
    apk add curl
    export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --bind-address=#{server_ip} --node-external-ip=#{server_ip} --flannel-iface=eth1"
    echo "INSTALL_K3S_EXEC : ${INSTALL_K3S_EXEC}"
    export KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
    echo "KUBECONFIG : ${KUBECONFIG}"

    curl -sfL https://get.k3s.io | sh -
    echo "Sleeping for 5 seconds to wait for k3s to start"
    sleep 15
    sudo cp /var/lib/rancher/k3s/server/node-token /vagrant_shared
    echo "/var/lib/rancher/k3s/server/node-token : $(cat /var/lib/rancher/k3s/server/node-token)"
    chmod 755 -R /vagrant_shared
    chmod 755 /etc/rancher/k3s/k3s.yaml
    sudo cp /etc/rancher/k3s/k3s.yaml /vagrant_shared
    echo "/etc/rancher/k3s/k3s.yaml : $(cat /etc/rancher/k3s/k3s.yaml)"
    SHELL

agent_script = <<-SHELL
    sudo -i
    apk add curl
    # export KUBECONFIG="/vagrant_shared/k3s.yaml"
    export KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
    echo "KUBECONFIG : ${KUBECONFIG}"
    # sudo mkdir -p ~/.kube
    sudo cp /vagrant_shared/k3s.yaml /etc/rancher/k3s/k3s.yaml
    echo "/etc/rancher/k3s/k3s.yaml : $(cat /etc/rancher/k3s/k3s.yaml)"
    export K3S_TOKEN_FILE=/vagrant_shared/node-token
    echo "K3S_TOKEN_FILE : ${K3S_TOKEN_FILE}"
    export K3S_URL=https://#{server_ip}:6443
    echo "K3S_URL : ${K3S_URL}"
    export INSTALL_K3S_EXEC="--flannel-iface=eth1"
    echo "INSTALL_K3S_EXEC : ${INSTALL_K3S_EXEC}"
    curl -sfL https://get.k3s.io | sh -
    SHELL

Vagrant.configure("2") do |config|
  # config.vm.box = "generic/alpine314"
  # config.vm.box = "generic/alpine38"
  config.vm.box = "generic/alpine37"

  config.vm.define "server", primary: true do |server|
    server.vm.network "private_network", ip: server_ip
    server.vm.synced_folder "./shared", "/vagrant_shared"
    server.vm.hostname = "server"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
    server.vm.provision "shell", inline: server_script
  end

  agents.each do |agent_name, agent_ip|
    config.vm.define agent_name do |agent|
      agent.vm.network "private_network", ip: agent_ip
      agent.vm.synced_folder "./shared", "/vagrant_shared"
      agent.vm.hostname = agent_name
      agent.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
      end
      agent.vm.provision "shell", inline: agent_script
    end
  end
end